import { Base64 } from 'js-base64';

// This file was generated by Mendix Studio Pro.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * @param {string} stringToEncode
 * @returns {Promise.<string>}
 */
async function Base64Encode(stringToEncode) {
    // BEGIN USER CODE
    return Base64.encode(stringToEncode);
    // END USER CODE
}

export { Base64Encode };
