// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// BEGIN EXTRA CODE
// END EXTRA CODE
/**
 * @returns {Promise.<void>}
 */
async function Reload() {
    // BEGIN USER CODE
    mx.reload();
    return new Promise(() => {
        // Never resolve this pormise to ensure that the next action in the nanoflow (if any)
        // will not be executed before the actual reload is happended.
    });
    // END USER CODE
}

export { Reload };
