#!/bin/sh

# Program name and download URL
PROGRAM_NAME="mendix-cli"
## might need to change the version. See for latest version at https://github.com/cinaq/mendix-model-exporter/releases
VERSION="v2.0.0"

# Path to the program in the hooks directory
PROGRAM_PATH="$(dirname $0)/$PROGRAM_NAME"

# Check if the program exists, download it if it does not
if [ ! -f "$PROGRAM_PATH" ]; then
    echo "Program not found, downloading..."
    OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
    ARCH="$(uname -m | tr '[:upper:]' '[:lower:]')"
    if [ "$OS" = "windows" ]; then
        EXT=".exe"
    else
        EXT=""
    fi
    if [ "$ARCH" = "aarch64" ]; then
        ARCH="arm64"
    fi
    DOWNLOAD_URL="https://github.com/cinaq/mendix-cli/releases/download/$VERSION/mendix-cli-$VERSION-$OS-$ARCH$EXT"
    curl -L -sf "$DOWNLOAD_URL" -o "$PROGRAM_PATH"
    chmod +x "$PROGRAM_PATH"
fi

# Execute the program
"$PROGRAM_PATH" export-model

# Check program execution result
if [ $? -ne 0 ]; then
    echo "Program failed, aborting commit."
    exit 1
fi

# Automatically stage changes made by your program
git add modelsource

# Exit with 0 to continue the commit process
exit 0
