$Type: Settings$ProjectSettings
Settings:
- $Type: Forms$WebUIProjectSettingsPart
  EnableMicroflowReachabilityAnalysis: true
  EnableNewWidgetGeneration: true
  EnableWidgetBundling: false
  ThemeModuleOrder: null
  UrlPrefix: p
  UseOptimizedClient: "No"
- $Type: Settings$IntegrationProjectSettingsPart
- $Type: Settings$ConfigurationSettings
  Configurations:
  - $Type: Settings$ServerConfiguration
    ApplicationRootUrl: http://localhost:8080/
    ConstantValues: null
    CustomSettings: null
    DatabaseName: default
    DatabasePassword: ""
    DatabaseType: Hsqldb
    DatabaseUrl: ""
    DatabaseUseIntegratedSecurity: false
    DatabaseUserName: ""
    ExtraJvmParameters: ""
    HttpPortNumber: 8080
    MaxJavaHeapSize: 0
    Name: Default
    OpenAdminPort: true
    OpenHttpPort: false
    ServerPortNumber: 8090
- $Type: Settings$ModelSettings
  AfterStartupMicroflow: ""
  AllowUserMultipleSessions: true
  BcryptCost: 12
  BeforeShutdownMicroflow: ""
  DefaultTimeZoneCode: ""
  EnableDataStorageOptimisticLocking: false
  FirstDayOfWeek: Default
  HashAlgorithm: BCrypt
  HealthCheckMicroflow: ""
  JavaVersion: Java21
  RoundingMode: HalfUp
  ScheduledEventTimeZoneCode: Etc/UTC
  UseDatabaseForeignKeyConstraints: true
  UseOQLVersion2: false
  UseSystemContextForBackgroundTasks: false
- $Type: Settings$ConventionSettings
  ActionActivityDefaultColors: null
  DefaultSequenceFlowLineType: BezierCurve
  LowerCaseMicroflowVariables: false
- $Type: Settings$LanguageSettings
  DefaultLanguageCode: en_US
  Languages:
  - $Type: Texts$Language
    CheckCompleteness: false
    Code: en_US
    CustomDateFormat: ""
    CustomDateTimeFormat: ""
    CustomTimeFormat: ""
- $Type: Settings$CertificateSettings
  Certificates: null
- $Type: Settings$WorkflowsProjectSettingsPart
  DefaultTaskParallelism: 3
  OnWorkflowEvent: null
  UserEntity: System.User
  UsertaskOnStateChangeEvent: null
  WorkflowEngineParallelism: 5
  WorkflowOnStateChangeEvent: null
- $Type: Settings$JarDeploymentSettings
  Exclusions: null
- $Type: Settings$DistributionSettings
  BasedOnVersion: ""
  IsDistributable: false
  Version: ""
