// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";

// BEGIN EXTRA CODE
    var isUploading = false;

    async function storeFileAndGetResourceUrl(file) {
        return URL.createObjectURL(file); // Saves the file to locally memory and returns a URL path to the Blob object.
    };

    function removeDomElements({fileInput, progressId}) {
        if(progressId) mx.ui.hideProgress(progressId); 
        if(fileInput) document.body.removeChild(fileInput);
        isUploading = false;    
    }

    function validateFileTypes ({acceptedTypes, fileType}) {
        if(!acceptedTypes && !fileType) return false;
        const accepted = acceptedTypes.split(",");
        return accepted.some(type => new RegExp(type).test(fileType));
    }

    function validateFileSize ({uploadedFile, maxSize}) {
        if(!uploadedFile && !maxSize) return false;
        const uploadedSize = uploadedFile.size / 1024 / 1024; // Convert to MB
        return uploadedSize < (maxSize.c[0] + 0.1); // 0.1 MB extra tolerance
    }
// END EXTRA CODE

/**
 * What does this JavaScript Action do?
 * 
 * This is a custom build JavaScript Action that triggers the file upload dialog box to open in your internet browser. 
 * 
 * Dependency Note: 
 * This JavaScript action should be used with the JavaScript Action called 'JS_RevokeUploadedFileFromMemory' so that the image uploaded is removed from local memory :)
 * 
 * Explanation of this JavaScript Action & Memory management.
 * 
 * We use createObjectURL() to upload and store files in local memory. We can access and cosume this in memory image resource via the URL path that is returned from the createObjectURL() method. 
 * 
 * However, each time you call createObjectURL(), a new object is created in memory, even if you've already created one for the same object. 
 * So each of these must be released by calling the JS Action called 'JS_RevokeUploadedFileFromMemory' when you no longer need them.
 * 
 * Browsers will release object URLs automatically when the document is unloaded; however, for optimal performance and memory usage, if there are safe times when you can explicitly unload them, you should do so with the JavaScriptAction called 'JS_RevokeUploadedFileFromMemory'.
 * @param {string} userDefined_mimeTypes
 * @param {Big} userDefined_fileUploadSize
 * @returns {Promise.<string>}
 */
export async function JS_UploadAndConvertToFileBlobURL(userDefined_mimeTypes, userDefined_fileUploadSize) {
	// BEGIN USER CODE
    return new Promise((resolve, reject) => {
        try {
            // Create and append the HTML input element to the body
            const fileInput = document.createElement("input");
            fileInput.style.position = "absolute";
            fileInput.style.left = "-9999px";
            fileInput.name = "fileupload";
            fileInput.id = "fileupload";
            fileInput.type = "file";
            if(userDefined_mimeTypes){
                fileInput.accept = userDefined_mimeTypes;
            }
            fileInput.multiple = false;
            fileInput.onchange = handleFileUpload;
            document.body.appendChild(fileInput);
            fileInput.addEventListener("cancel", () => resolve("uploadCancelled"));
            fileInput.click();

            // A function used to validate & store the uploaded file to local memory.
            function handleFileUpload(event) {
                isUploading = true;
  
                const newFile = event.target.files[0];
                const progressId = mx.ui.showProgress(null, true);

                // Check if the uploaded file type matches the user defined accepted types.
                if (!validateFileTypes({acceptedTypes: fileInput.accept, fileType: newFile.type})) {
                    removeDomElements({fileInput, progressId});
                    resolve("fileTypeNotAccepted");
                    return;
                }
                // Check if the uploaded file matches the user defined upload size.
                if (!validateFileSize({uploadedFile: newFile, maxSize: userDefined_fileUploadSize})) { 
                    removeDomElements({fileInput, progressId});
                    resolve("fileSizeNotAccepted");
                    return;
                }
                // Store file locally on users device and return path to resource.
                storeFileAndGetResourceUrl(newFile).then((fileBlobURL) => {
                    if(fileBlobURL && typeof fileBlobURL === "string") {
                        removeDomElements({fileInput, progressId});
                        resolve(fileBlobURL);
                    } else {
                        removeDomElements({fileInput, progressId});
                        resolve("fileNotConverted");
                    }
                })
                return;
            };
        } catch (error) {
            reject(error);
        }
    });
	// END USER CODE
}
