// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.StringUtils;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Reads the contents form the provided file document, using the specified encoding, and returns it as string.
 */
public class StringFromFile extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __source;
	private system.proxies.FileDocument source;
	private communitycommons.proxies.StandardEncodings encoding;

	public StringFromFile(IContext context, IMendixObject source, java.lang.String encoding)
	{
		super(context);
		this.__source = source;
		this.encoding = encoding == null ? null : communitycommons.proxies.StandardEncodings.valueOf(encoding);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.source = this.__source == null ? null : system.proxies.FileDocument.initialize(getContext(), __source);

		// BEGIN USER CODE
		Charset charset = StandardCharsets.UTF_8;
		if (this.encoding != null)
			charset = Charset.forName(this.encoding.name().replace('_', '-'));
		return StringUtils.stringFromFile(getContext(), source, charset);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringFromFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
