// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package communitycommons.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import communitycommons.StringUtils;

/**
 * True if a string can be simplified by the removal of diacritics.
 */
public class IsStringSimplified extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String value;

	public IsStringSimplified(IContext context, java.lang.String value)
	{
		super(context);
		this.value = value;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return StringUtils.isStringSimplified(this.value);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IsStringSimplified";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
