// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package feedbackmodule.actions;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class XSS_Sanitizer extends CustomJavaAction<java.lang.String>
{
	private java.lang.String stringToSanitize;

	public XSS_Sanitizer(IContext context, java.lang.String stringToSanitize)
	{
		super(context);
		this.stringToSanitize = stringToSanitize;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

        //It's a simple XSS sanitation with regex replace.
        String sanitizedString = sanitize(stringToSanitize);
        return sanitizedString;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "XSS_Sanitizer";
	}

	// BEGIN EXTRA CODE
    public static String sanitize(String input) {
        if (input == null || input.isEmpty()) {
            return input;
        }

        // Remove all occurrences of <script> tags and their contents
        input = input.replaceAll("(?i)<script[^>]*>.*?</script>", "");

        // Remove all event handler attributes (e.g., onclick, onmouseover)
        input = input.replaceAll("(?i)\\bon\\w+\\s*=\\s*(\"[^\"]*\"|'[^']*'|[^\\s>]+)", "");

        // Remove all javascript: URLs
        input = input.replaceAll("(?i)javascript:", "");

        // Remove all <iframe> tags
        input = input.replaceAll("(?i)<iframe[^>]*>.*?</iframe>", "");

        // Remove all <object> tags
        input = input.replaceAll("(?i)<object[^>]*>.*?</object>", "");

        // Remove all <embed> tags
        input = input.replaceAll("(?i)<embed[^>]*>.*?</embed>", "");

        // Remove all <applet> tags
        input = input.replaceAll("(?i)<applet[^>]*>.*?</applet>", "");

        // Remove all <meta> tags that could potentially cause redirection
        input = input.replaceAll("(?i)<meta[^>]*http-equiv[^>]*>", "");

        // Remove all other potentially dangerous HTML tags
        Pattern pattern = Pattern.compile("<[^>]*(>|$)");
        Matcher matcher = pattern.matcher(input);
        input = matcher.replaceAll("");

        return input;
    }
	// END EXTRA CODE
}
