name: Continuous Integration

on:
  push:
    branches:
    - "*"
  pull_request:
    branches: [ main ]

jobs:

  CLI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22

    - name: Build
      run: go build -o bin/mxlint "./"

    - name: Test
      run: go test -v ./...

    - name: Test subcommand export-model mpr-v1
      run: |
        bin/mxlint export-model --mode basic -i resources/app-mpr-v1 -o resources/modelsource-v1
        git diff --exit-code resources/modelsource-v1 

    - name: Test subcommand export-model mpr-v2
      run: |
        bin/mxlint export-model --mode basic -i resources/app-mpr-v2 -o resources/modelsource-v2
        git diff --exit-code resources/modelsource-v2

    - name: Test subcommand lint
      run: ./bin/mxlint lint --xunit-report report.xml --rules ./resources/rules -m resources/app-mpr-v1

    - name: Test subcommand test-rules
      run: ./bin/mxlint test-rules --rules ./resources/rules
